spring.application.name=taskmanager

server.port=8088

# postgres db
spring.datasource.url=jdbc:postgresql://localhost:5432/taskdb
spring.datasource.username=postgres
spring.datasource.password=root

# JPA / hibernate
spring.jpa.hibernate.ddl-auto=update
